### ISSUE TITLE
[META] Rollover indices lifecycle

### ISSUE THREAD

**Issue by HonzaKral** [elastic/curator#1046]
## Rollover indices

By rollover indices we mean a group of indices and an alias that relies on the
`_rollover` API to operate. We can assume that each group has a single alias
`PREFIX` (for example `"prod-apache-logs"`) and a series of indices that follow the naming pattern of
`PREFIX-\d{6}` (`"prod-apache-logs-000001"` - `"prod-apache-logs-000007"`). The 
alias points to the last index in the series, this index
(`"prod-apache-logs-000007"`) is the index that is still being written to, we
call that the `active` index.

### Lifecycle

In various points in an index lifecycle we might want to perform operation on
either `active` or `inactive` indices, for example:

* snapshot all `active` indices every hour
* force merge indices that are no longer `active`

We also need to address indices that belong to a certain time period. Since a
rollover index can belong to multiple time periods (as rollover is often
size-based and not time-based) we need to identifyy possibly all of them to be
able to: 

* snapshot all indices containing January data into `archive-201701` repository

## Proposed enhancements

- [x] add `intersect` value to `stats_result` parameter of the `period` filter
which will identify those indices where `min_value <= range_to AND max_value >=
range_from` (the `period` of the filter and of the index data intersect) (#1045)

- [x] add `pattern` parameter to `count` filter that would allow it to operate
within groups: given indices `[logs-1, logs-2, logs-3, metrics-1, metrics-2]`
the filter `{filtertype: count, count: 1, pattern: '^(.*)-\d$', reverse: true}` will
produce `[logs-3, metrics-2]` - a list composed of `active` indices for
every prefix. (#1044)

 - [x] allow absolute time for `period` filter where we cannot filter for same by simple `pattern` filter like we can for time-based indices.(#1047)

**Comment by untergeek** [comment]
These have been addressed by #1076, #1081, and #1085
